version: '3.8'

services:

  dns:
    build: ./bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.2

  load_balancer1:
    image: nginx:latest
    volumes:
      - ./nginx/conf/load_balancer1.conf:/etc/nginx/conf.d/default.conf
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.3
    depends_on:
      - caching-server1
      - caching-server2

  caching-server1:
    image: nginx:latest
    volumes:
      - ./nginx/conf/caching-server.conf:/etc/nginx/conf.d/default.conf
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.5
    depends_on:
      - backend-with-images
      - dns

  caching-server2:
    image: nginx:latest
    volumes:
      - ./nginx/conf/caching-server.conf:/etc/nginx/conf.d/default.conf
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.6
    depends_on:
      - backend-with-images
      - dns

  load_balancer2:
    image: nginx:latest
    volumes:
      - ./nginx/conf/load_balancer2.conf:/etc/nginx/conf.d/default.conf
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.4
    depends_on:
      - caching-server3
      - caching-server4

  caching-server3:
    image: nginx:latest
    volumes:
      - ./nginx/conf/caching-server.conf:/etc/nginx/conf.d/default.conf
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.7
    depends_on:
      - backend-with-images
      - dns

  caching-server4:
    image: nginx:latest
    volumes:
      - ./nginx/conf/caching-server.conf:/etc/nginx/conf.d/default.conf
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.8
    depends_on:
      - backend-with-images
      - dns


  backend-with-images:
    image: nginx:latest
    volumes:
      - ./nginx/conf/backend.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/images:/images
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.9
    depends_on:
      - dns

  client:
    build: curlimages/curl:latest
    dns: 10.5.0.2
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.11
    depends_on:
      - dns
    command: curl -I  http://cdn.zhuk.com/cat.jpg

  siege:
    image: ecliptik/docker-siege
    dns: 10.5.0.2
    command: siege -c255 -t15S "http://cdn.zhuk.com/cat.jpg"
    networks:
      cdnnetwork:
        ipv4_address: 10.5.0.10


networks:
  cdnnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16